[package]
name = "mdkloc"
version = "2.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
unicode-normalization = "0.1"
glob = "0.3"
colored = "2.2.0"
terminal_size = "0.4.3"

[dev-dependencies]
tempfile = "3.3"
